### ISSUE TITLE
Dependency puppetlabs/dsc (>= 1.5.0 < 2.0.0) incorrect due to missing dsc_xdnsserveraddress

### ISSUE THREAD

**Issue by smr1983** [beergeek/active_directory#3]
In at least version 1.9.2 and higher of puppetlabs/dsc dsc_xdnsserveraddress is missing. I haven't looked at the exact version, because I need 1.9.2+ for other features.

**Comment by beergeek** [comment]
Thanks @smr1983 I will look into this and get a fix out

**Comment by beergeek** [comment]
@smr1983 I have released version `0.4.0` on the Forge
